const router = require("express").Router()
const authorRouter = require("./author.routes")
const socialRouter = require("./social.routes")
const authorSocialRouter = require("./author_social.routes")
const authRouter = require("./auth.routes")
const dictinaryRouter = require("./dictionary.routes")
const topicRouter = require("./topic.route")
const categoryRouter = require("./category.route")
const descriptionRouter = require("./description.route")
const synonymRouter = require("./synonym.route")
const desc_topicRouter = require("./desc_topic.route")
const tagRouter = require("./tag.route")

router.use("/author", authorRouter)
router.use("/social", socialRouter)
router.use("/authorSocial", authorSocialRouter)
router.use("/auth", authRouter)
router.use("/dictionary", dictinaryRouter)
router.use("/topic", topicRouter)
router.use("/category", categoryRouter)
router.use("/description", descriptionRouter)
router.use("/synonym", synonymRouter)
router.use("/desc_topic", desc_topicRouter)
router.use("/tag", tagRouter)

module.exports = router